
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import Menu from "./components/menu/Menu";
import CanvasAnimation from "./components/CanvasAnimation/CanvasAnimation";
import BackgroundAnimation from "./components/common-component/background-animation/BackgroundAnimation";
import Footer from "./components/footer/Footer";
import Contact from "./components/contact/Contact";
import AOSInit from "./components/aos-init/AOSInit";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tomal Ahmed Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AOSInit />
        <Menu />
        {children}
        <Contact />
        <Footer />
        <BackgroundAnimation
          color={[1, 1, 1]}
          mouseReact={true}
          amplitude={0.1}
          speed={1.0}
        />
        {/* <CanvasAnimation /> */}
      </body>
    </html>
  );
}
